export const JOB_TITLES = [
  'Software Engineer',
  'Senior Software Engineer',
  'Engineering Manager',
  'Sales Representative',
  'Account Executive',
  'Sales Manager',
  'Marketing Coordinator',
  'Marketing Specialist',
  'Marketing Manager',
  'Financial Analyst',
  'Senior Financial Analyst',
  'Finance Manager',
  'HR Coordinator',
  'HR Business Partner',
  'HR Manager',
  'Operations Analyst',
  'Operations Specialist',
  'Operations Manager',
  'Legal Analyst',
  'Senior Counsel',
  'Legal Manager',
  'Product Analyst',
  'Product Manager',
  'Senior Product Manager',
  'UX Designer',
  'Senior UX Designer',
  'Design Manager',
  'Customer Success Associate',
  'Customer Success Manager',
  'Director of Customer Success',
] as const;

export const DEPARTMENTS = [
  'Engineering',
  'Sales',
  'Marketing',
  'Finance',
  'HR',
  'Operations',
  'Legal',
  'Product',
  'Design',
  'Customer Success',
] as const;

export const COUNTRIES = [
  'United States',
  'United Kingdom',
  'Germany',
  'India',
  'Canada',
  'Australia',
  'France',
  'Brazil',
] as const;

export const EMPLOYMENT_TYPES = [
  { value: 'FULL_TIME', label: 'Full Time' },
  { value: 'PART_TIME', label: 'Part Time' },
  { value: 'CONTRACT', label: 'Contract' },
] as const;
